version: "3"
services:
  discovery-service:
    image: discovery-service
    ports:
      - "8761:8761"
  gateway-service:
    image: gateway-service
    depends_on:
      - user-service
    ports:
      - "8080:8080"
  user-service:
    image: user-service
    depends_on:
      - postgres
      - discovery-service
    ports:
      - "8001:8001"
  postgres:
    image: postgres-moonlight
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 00zomifi
      POSTGRES_DB: moonlight